<?php
[%getuser]
if(!$USER['islogin'])
 headecho::gotologin('',true);
$dir=str::word($_REQUEST['dir']);
if(!$_REQUEST['go'])
{
?>
[html=Q浏HuR3种子制作器]
[form=post,read.php?[u.b]&amp;[u.c]&amp;[u.p]&amp;dir=<%=$dir%>[u.sid]]
名字:[input=name][/input][br]
第一条的地址:[br][input=url][/input][br]
[sel=fanye][op=0]向上[/op][op=1]向下[/op][/sel]翻页[br]
共[input=count,2][/input]条[br]
序号从h[input=qi,2]1[/input].jpg起[sel=step][op=1]递增[/op][op=0]递减[/op][/sel][br]
[submit=go]开始[/submit]
[/form]
<?php
}
else
{
$url=$_REQUEST['url'];
$h=new httplib;
$h->open($url);
$h->send();
?>
[html=代码页]
<%=code::html($h->response())%>
<?php
}
?>
[foot][/html]