[html=XDownload种子生成器]
[form=post,read.php?[u.b]&amp;[u.c]&amp;pid=xurl_set[u.sid]]
超时时间(秒):[input=timeout]60[/input][br]
重试次数:[input=restart]5[/input][br]
接入点(分别设置<input name="every" type="checkbox" value="1" />):[input=apn]cmmm[/input][br]
代理服务器(cmwap需要填[url]10.0.0.172:80[/url]):[input=proxy][/input][hr]
任务数:[input=count]1[/input][br]
单任务分卷数:[input=icount]5[/input][br]
[submit=go]开始填写[/submit]
[/form]
[/html]