<?php
[%getuser]
if(!$USER['islogin'])
 headecho::gotologin('',true);
$dir=str::word($_REQUEST['dir']);
if(!$_POST['go'])
{
?>
[html=插入名片]
[head]
[form=post,read.php?[u.b]&amp;[u.c]&amp;[u.p]&amp;dir=<%=$dir%>[u.sid]]
给你的名片取一个合适的名字吧:[br][input=name][/input][br]
需要附加的文字，可以写在这里，有三个输入框的空间:[br][input=extra1,2][/input][input=extra2,2][/input][input=extra3,2][/input][br]
[submit=go]新建[/submit][anchor=post,新建,read.php?[u.b]&amp;[u.c]&amp;[u.p]&amp;dir=<%=$dir%>[u.sid]][pst=name][pst=extra1][pst=extra2][pst=extra3][/anchor]
[/form]
<?php
}
else
{
$eid=url::b64e(pack('V',time()));
$title=$_POST['name'] or $title='新建名片';
$extra=$_POST['extra1'].$_POST['extra2'].$_POST['extra3'];
$s=new session($USER['uid'],'urlbook.'.$dir,0,array($eid));
$s[$eid]=array(
'title'=>$title,
'extra'=>$extra,
);
headecho::location('read.php?[%%u.b]&cid=urlbook&pid=card&dir='.$dir.'[%%u.sid]',true);
}
?>[hr]返回[read=,urlbook,card&amp;dir=<%=$dir%>]我的地址簿[/read]-[read=,index,]首页[/read]
[br][time][foot]
[/html]