<?php
[%getuser]
if(!$USER['islogin'])
 headecho::gotologin('',true);
$dir=str::word($_REQUEST['dir']);
$eid=str::word($_REQUEST['eid']);
if(!$_POST['go'])
{
?>
[html=插入信息]
[head]
[form=post,read.php?[u.b]&amp;[u.c]&amp;[u.p]&amp;dir=<%=$dir%>&amp;eid=<%=$eid%>[u.sid]]
给你的信息取一个合适的名字吧:[br][input=name][/input][br]
信息类型:[sel=type][op=url]网址[/op][op=tel]电话号码[/op][/sel][br](以后会加更多)[br]
信息的内容写在这里，有三个输入框的空间:[br][input=nr1][/input][input=nr2][/input][input=nr3][/input][br]
[submit=go]插入[/submit][anchor=post,插入,read.php?[u.b]&amp;[u.c]&amp;[u.p]&amp;dir=<%=$dir%>&amp;eid=<%=$eid%>[u.sid]][pst=name][pst=nr1][pst=nr2][pst=nr3][/anchor]
[/form]
<?php
}
else
{
$title=$_POST['name'] or $title='新建信息';
$nr=$_POST['nr1'].$_POST['nr2'].$_POST['nr3'];
$type=str::word($_REQUEST['type']);
switch($type)
 {
case 'url':
 $nr=str_replace('&amp;','&',$nr);
 if(!preg_match('/^[a-zA-Z0-9_]+:/',$nr))
  $nr='http://'.$nr;
break;
case 'tel':
 $nr=preg_replace('![[xor]\+0-9]!','',$nr);
break;
 }
$s=new session($USER['uid'],'urlbook.'.$dir,0,array($eid));
$info=$s[$eid];
$info[]=array(
'title'=>$title,
'value'=>$nr,
'type'=>$type
);
$info['count']++;
$s[$eid]=$info;
headecho::location('read.php?[%%u.b]&cid=urlbook&pid=info&dir='.$dir.'&eid='.$eid.'[%%u.sid]',true);
}
?>[hr]返回[read=,urlbook,info&amp;dir=<%=$dir%>&amp;eid=<%=$eid%>]我的名片[/read]-[read=,index,]首页[/read]
[br][time][foot]
[/html]