<?php
/*
url
name
dir
code
go
*/
[%getuser]
$url=$_SERVER['QUERY_STRING'];
$pos=strpos($url,'&url=');
if($pos!==false)
{
$_POST=$_REQUEST=url::getqueryarray(substr($url,0,$pos));
$url=substr($url,$pos+5);
if($code=$_REQUEST['code'])
 {
if($code=='url')
 $func='urldecode';
elseif($code=='base64')
 $func='base64_decode';
else
 $func='';
if($func)
 $_POST['url']=$func($url);
else
 $_POST['url']=$url;
unset($func);
 }
else
 $_POST['url']=urldecode($url);
unset($code);
if($_REQUEST['go'])
 $_POST['go']='小文件下载';
else
 $_POST['go']='新建';
}
unset($url,$pos);
if(!$_REQUEST['dir'])
{
$s=new session($USER['uid'],'dir',0,'limit 1');
foreach($s as $n=>$v)
 {$_REQUEST['dir']=$n;}
unset($s,$n,$v);
}
$PAGE['cid']='fat32';
$PAGE['pid']='newbin';
include ubb::page($PAGE['bid'],fat32,newbin);
?>