<?php
[%getuser]
if(!$USER['islogin'])
 headecho::gotologin('',true);
if(!$_POST['go'])
{
?>
[html=<%=$USER<('name')>%>-修改密码]
[head]
[form=post,read.php?[u.b]&amp;cid=user&pid=gai_pass[u.sid]]
原密码:[input=pass0][/input][br](如果你忘了原密码，请[read=,user,gai_pass_mibao]通过密保修改密码[/read])[br]新密码:[input=pass][/input][br](密码可以是任何手机能打出的字符，包括中文。但不建议在密码中用换行符)[br]
[submit=go]修改[/submit][anchor=post,修改,read.php?[u.b]&amp;cid=user&amp;pid=gai_pass[u.sid]][post=pass0]$(pass0)[/post][post=pass]$(pass)[/post][post=pass2]$(pass2)[/post][/anchor]
[/form]<?php
}
else
{
$pass0=$_POST['pass0'];
$pass=$_POST['pass'];
$pass2=$_POST['pass2'];
if(md5($pass0)!=$USER['pass'])
 {
?>
[html=很抱歉，出错了]
数据库说：“我记得你的原密码不是这样的，你再想想吧。[br]如果实在想不起来，[read=,user,gai_pass_mibao]密保[/read]可以帮你。”
<?php
 }
elseif($pass2=='')
 {
?>
[html=确认密码]
[form=post,read.php?[u.b]&amp;cid=user&amp;pid=gai_pass[u.sid]]
你还记得你的新密码吗？[br]确认密码:[input=pass2][/input][br]
[h=pass]<%=$pass%>[/h][h=pass0]<%=$pass0%>[/h]
[submit=go]确认[/submit][anchor=go,确认,read.php?[u.b]&amp;[u.c]&amp;[u.p][u.sid]][pst=pass2][post=pass]<%=$pass%>[/post][post=pass0]<%=$pass0%>[/post][/anchor]
[/form]
<?php
 }
elseif($pass!=$pass2)
 {
?>
[html=出错啦]
不会吧，你这么快就忘了你的密码了？？[br]赶快返回修改。
<?php
 }
else
 {
$sql="update ".DB_A."user set pass='".md5($pass)."' where  uid=$USER[uid]";
$db=user::conn();
if(!$db->exec($sql))
  {
?>
[html=出错啦！]
数据库说：“我不知道怎么啦，总之你的密码更新失败啦！请尝试重新提交。”
<?php
  }
else
  {
user::setsid($USER['uid'],$USER['name'],$pass,time()+DEFAULT_LOGIN_TIMEOUT);
?>
[html=密码修改成功]
密码修改成功！[br]用户身份sid已更新，你需要[read=,user,login]用新密码重新登陆[/read]。
<?php
  }
 }
}
?>
[hr]返回[read=,user,]用户中心[/read]-[read=,index,]首页[/read][br][time][foot]
[/html]